### ISSUE TITLE
venn-abers algorithim

### ISSUE THREAD

**Issue by farzadhallaji** [PaschalisAthan/Master_Thesis#1]
what is the main venn-abers function?

**Comment by farzadhallaji** [comment]
can you please send me the source code of venn-abers?
email : farzadhallaji@gmail.com

**Comment by PaschalisAthan** [comment]
In my case, Venn-ABERS predictors are being used on a Support Vector Machines underlying algorithm in order to predict the probability of the binding activity of a molecule.

The whole modelling procedure (which probably contains the Venn-ABERS source code) is done by using CPSign, a software created by one of my colleagues, for which you need a license.

**Comment by farzadhallaji** [comment]
Thanks,
I send emails for get license but i don't receive any response.
